# Site settings
title: 'Coming Together'
subtitle: 'in Skokie & Niles Township'
email: rosbha@d219.org
series_title: '¡Viva!'
series_dates: 'February to March 2015'
description: 'A cultural and literary series exploring the Latino culture in our community.'
baseurl: "" # the subpath of your site, e.g. /blog/
currentyear: "2016"
url: "http://comingtogether.in" # the base hostname & protocol for your site
permalink: /events/:year/:month/:day/:title
exclude: [README.md, bower.json, package.json, bower_components, scss, node_modules, gulpfile.js, working, events/working]
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
prose:
    rooturl: "events/_posts"
    siteurl: "http://comingtogether.in"
    metadata:
        events/_posts:
            - name: "layout"
              field:
                element: "hidden"
            - name: "title"
              field:
                element: "text"
                label: "Title"
            - name: "subtitle"
              field:
                element: "hidden"
            - name: "location"
              field:
                element: "text"
                label: "Location"
            - name: "date"
              field:
                element: "text"
                label: "Date"
                help: "Must be yyyy-mm-dd hh:mm:ss -0600"
            - name: "times"
              field:
                element: "text"
                label: "Times"
            - name: "audiences"
              field:
                element: "multiselect"
                label: "Audience"
                alterable: true
                options:
                  - name: "Adults"
                    value: "Adults"
                  - name: "Teens"
                    value: "Teens"
                  - name: "Kids/Family"
                    value: "Kids/Family"
                  - name: "All ages"
                    value: "All ages"
            - name: "types"
              field:
                element: "select"
                label: "Event type"
                options:
                  - name: "Books/Authors"
                    value: "Books/Authors"
                  - name: "Film"
                    value: "Film"
                  - name: "Kids/Family"
                    value: "Kids/Family"
                  - name: "Lecture"
                    value: "Lecture"
                  - name: "Performance"
                    value: "Performance"
                  - name: "Workshop"
                    value: "Workshop"
            - name: "registration"
              field:
                element: "text"
                label: "Registration URL"
            - name: "canceled"
              field:
                element: "select"
                label: "Canceled?"
                options:
                  - name: "No"
                    value: "No"
                  - name: "Yes"
                    value: "Yes"
# Build settings
markdown: kramdown
